language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - cd package
script:
  - echo "skipping tests"
  - npm run build
before_deployment:
  - cd ../sample
deploy:
  provider: script
  script: npm run deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branches:
      only:
        - gh-pages
