language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - cd package
script:
  - echo "skipping tests"
  - npm run build
before_deployment:
  - cd .. && cd sample
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ydhmTcuJ0QpZN2qEkiN3hw # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: gh-pages
