language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - cd package
script:
  - echo "skipping tests"
  - npm run build
before_deploy:
  - cd ../sample && npm i && git config --global user.email amauriairesfilho@gmail.com && git config --global user.name "AmauriAires"
deploy:
  provider: script
  script: npm run deploy
  skip-cleanup: true
  keep-history: true
  on:
    branches:
      only:
        - gh-pages
